server:
  port: 9092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finalproject
    username: root
    password: root

  application:
    name: admin  # must match admin.yml in repo
  config:
    import: optional:configserver:http://localhost:9094
